from django.db import models

#line in relation to the home team
class Game(models.Model):
  date = models.DateTimeField()
  teamH = models.CharField(max_length = 1000)
  scoreH = models.IntegerField()
  firstDownH = models.IntegerField()
  thirdDownPctH = models.FloatField()
  rushAttH = models.IntegerField()
  rushYdsH = models.IntegerField()
  passAttH = models.IntegerField()
  passCompH = models.IntegerField()
  passYdsH = models.IntegerField()
  passIntH = models.IntegerField()
  fumblesH = models.IntegerField()
  sackYdsH = models.IntegerField()
  penYdsH = models.IntegerField()
  timePosH = models.IntegerField()
  teamA = models.CharField(max_length = 1000)
  scoreA = models.IntegerField()
  firstDownA = models.IntegerField()
  thirdDownPctA = models.FloatField()
  rushAttA = models.IntegerField()  
  rushYdsA = models.IntegerField()
  passAttA = models.IntegerField()
  passCompA = models.IntegerField()
  passYdsA = models.IntegerField()
  passIntA = models.IntegerField()
  fumblesA = models.IntegerField()
  sackYdsA = models.IntegerField()
  penYdsA = models.IntegerField()
  timePosA = models.IntegerField()
  line = models.FloatField()
